version: "3.8"

services:
  app-flotapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-flotapp
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY:-your-gemini-api-key-here}
    ports:
      - "8111:3000"
    restart: unless-stopped
